### ISSUE TITLE
Can't add new docs

### ISSUE THREAD

**Issue by ourlaw** [nk-o/docspress#14]
Hello, 
After my fresh install on my WordPress v5.2.4 I face with this issue:
![image](https://user-images.githubusercontent.com/18216265/68085548-00d77c80-fe7d-11e9-8407-294434eec3f8.png)
Also, I tried in my local machine using Xampp, the same issue.
Please consider my php version is 7.2

**Comment by nk-o** [comment]
Hi.

Most probably conflicted with 3rd-party plugins. How it should look:

![image](https://user-images.githubusercontent.com/14810891/68804097-0e0d1c00-0672-11ea-92f8-13077746f7a5.png)

**Comment by ourlaw** [comment]
Hi, after checking, I realized this plugin has conflict with Filebird:
https://wordpress.org/plugins/filebird/
