### ISSUE TITLE
Search not working when used with Elementor Pro template

### ISSUE THREAD

**Issue by parasshah195** [nk-o/docspress#18]
On doing the search, it's throwing this error in console - `Uncaught TypeError: Cannot read property 'outerHTML' of undefined` in `assets/js/script.js` at https://github.com/nk-o/docspress/blob/169dc3941cc064046c7b07addec8d5d236f8eb5e/src/assets/js/script.js#L64

To debug, I enabled the troubleshooting mode, only kept the DocsPress and default theme activated and it worked just fine, then I enabled Elementor and Elementor Pro, and it stopped working.

To find the root cause, I logged the output of `$data` and realized that in the default theme setup, the array of result contained the `.docspress-search-list` element whereas in the Elementor template, the length of matching element was 0.

We are using the plugin here - https://pixify.net/kb/designer-powerup-for-elementor/getting-started/

@nk-o, can you please look into this?

**Comment by nk-o** [comment]
Hi.

DocsPress uses a custom template for search output. For example, look at the page output, that should be - https://nkdev.info/?s=demo&post_type=docs&child_of=825584

And see what rendered on your site - https://pixify.net/?s=quick&post_type=docs&child_of=4252

Most probably, Elementor replaces templates with higher priority and our code can't output anything.

**Comment by parasshah195** [comment]
@nk-o, thanks for the detailed explanation. I was using Elementor Pro to set those templates on the whole knowledgebase archives. As soon as I excluded that template from search results, the docs search functionality started working as expected.

Thanks a lot again. Much appreciated.
