### ISSUE TITLE
A different template to facilitate a better UX for more complex use cases?

### ISSUE THREAD

**Issue by parasshah195** [nk-o/docspress#20]
We have multiple plugins and each category has lots of long articles. The left navigation sidebar is nice, but that also means that if we have all article titles enabled, it becomes pretty long and hard to find.

While surfing on the Slack's help website, I realized that it's kinda the perfect solution to make it easier to find articles as well as put it in a better UI with Table of Contents for each article to skim through quickly.

Any plans to add a template like that? (Slack eg: https://slack.com/intl/en-in/help/articles/360017938993-What-is-a-channel)

If not, can you quickly guide me through how can I override the templates from theme (is that possible?) or how do I proceed to create my own template in a non-destructible way so that the plugin updates don't affect it?

**Comment by nk-o** [comment]
Hey.

We are using Table of Contents block from Ghost Kit - https://ghostkit.io/blocks/table-of-contents/

It is placing as a static block, but you can add custom styles and make it sticky, as we did here - https://lazyblocks.com/documentation/blocks-controls/

Hope it will help you.
