### ISSUE TITLE
Option to remove header bounce

### ISSUE THREAD

**Issue by austere-rm** [nk-o/docspress#28]
Hi, I'm loving this plugin, and thanks for building it and making it available.

I'm customizing the CSS to match my theme and I would like to remove the bouncing header and popup article count with this class:

```
.docspress-archive .docspress-archive-list>.docspress-archive-list-item .docspress-archive-list-item-title>span h2
```

I can't find any CSS :hover to disable, so wondering if it's JS or jQuery instead?

Would you consider an option to disable animations? Or is there a fix for this I can apply locally?

Thanks.

**Comment by nk-o** [comment]
You need to look at this SCSS part:

https://github.com/nk-o/docspress/blob/84e920e7b43225ce4c3602b8907921d670868c8c/src/assets/css/style.scss#L750-L759

No, I don't think there will be an option to disable animations.
